### ISSUE TITLE
PATH_INFO / SCRIPT_NAME with mod_ruby

### ISSUE THREAD

**Issue by calh** [mikeowens/ModRuby#8]
Hi @mikeowens,

I'm having another really odd problem that's difficult to troubleshoot.  While I don't think this issue is specific to mod_ruby, it has something to do with mod_ruby triggering behavior in either Apache or Passenger which sets the environment varaibles `PATH_INFO` and `SCRIPT_NAME` to the incorrect paths.

I'm not able to recreate it with docker, so I'm going to try my best on describing my setup.

This is running ruby 2.5.8p224, Passenger 6.0.4, Apache 2.4.6-90 (CentOS 7), and the freshest mod_ruby master code.

```
<VirtualHost *:80>
  ServerName  internal.myname.com
  RailsEnv              development
  PassengerEnabled off
  <Location ~ "/^myapp">
    PassengerEnabled on
    PassengerAppRoot /home/httpd/myapp/dev
  </Location>
</VirtualHost>
```

Simple sinatra app:
```
module HTTP_Auth
  class Server < Sinatra::Base
        get '/get_domain/test' do
             ENV.inspect  # runs
        end
        get '/myapp/get_domain/test' do
             ENV.inspect  # never runs
        end
```

```
$ curl http://internal.myname.com/myapp/get_domain/test
...
"REQUEST_URI"=>"/myapp/get_domain/test",
"SCRIPT_NAME"=>"/myapp"
"PATH_INFO"=>"/get_domain/test"
```

When mod_ruby.so is loaded, something triggers the `SCRIPT_NAME` and `PATH_INFO` paths to be populated, and they're incorrect.  Sinatra and Rails seem to short circuit whatever they do and trust the `PATH_INFO` variable, which doesn't match any of the routing regex rules.  All of our apps are written with the awareness of the full path, and expect `/myapp/whatever` to be the scope for all of the routing config.

If I comment out loading mod_ruby.so, none of those variables are present, and the apps (Sinatra and Rails) still correctly determine the paths and work normally.

How can I forcefully disable Apache from attempting to parse and set these variables?  I've tried messing with [AcceptPathInfo](https://httpd.apache.org/docs/2.4/mod/core.html#acceptpathinfo), but nothing worked.  I've tried poking through the mod_ruby initialization and Apache source to see what might affect triggering the `PATH_INFO` and `SCRIPT_NAME`, but haven't found anything useful yet.

Any advice you have here would be appreciated!

**Comment by mikeowens** [comment]
Looking around, the only thing I can see offhand that interacts with the environmental variables is `ruby_request_handler()` in `module.cpp` which calls  `Request::setup_cgi()` in `request.cpp`, which in turn calls the Apache functions `ap_add_cgi_vars()` and `ap_add_common_vars()` which are described here:

https://httpd.apache.org/docs/current/mod/mod_cgi.html

According to this, it includes `PATH_INFO` as one of the variables that gets set. It could be that the order in which the handlers are called causes the `PATH_INFO` to be overwritten/clobbered with some original value in Apache. You could test this by commenting these calls out in `request.cpp`, recompiling `mod_ruby` and then running to see if that is the cause.

**Comment by calh** [comment]
Yep!  Commenting out `ap_add_cgi_vars()` [here](https://github.com/mikeowens/ModRuby/blob/master/src/request.cpp#L179) prevented `PATH_INFO` and `SCRIPT_NAME` from being populated, and my apps work as expected.

Are these CGI vars required for any pieces of the mod_ruby API calls that are exposed and documented to developers?  I'm just wondering if I could delete the line and submit a PR, or if you'd want something more sophisticated like an option toggle for it.

**Comment by mikeowens** [comment]
Well it would be better to modify one layer up and figure out which handler you are using and maybe make some change there. That function is actually useful and needed if you want CGI vars. Can you tell which handler you are using? We could maybe create an option to turn CGI off there.

**Comment by calh** [comment]
In this particular test case, I'm not using any handlers at all.  It's just Passenger, and the only difference is that I have mod_ruby loaded along side the rest of the modules.

**Comment by calh** [comment]
Here's a list of my loaded modules, if this helps:

```
# apachectl -M
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 allowmethods_module (shared)
 auth_basic_module (shared)
 auth_digest_module (shared)
 authn_anon_module (shared)
 authn_core_module (shared)
 authn_dbd_module (shared)
 authn_dbm_module (shared)
 authn_file_module (shared)
 authn_socache_module (shared)
 authz_core_module (shared)
 authz_dbd_module (shared)
 authz_dbm_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_owner_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 cache_disk_module (shared)
 data_module (shared)
 dbd_module (shared)
 deflate_module (shared)
 dir_module (shared)
 dumpio_module (shared)
 echo_module (shared)
 env_module (shared)
 expires_module (shared)
 ext_filter_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 info_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_magic_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 remoteip_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_plain_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_memcache_module (shared)
 socache_shmcb_module (shared)
 status_module (shared)
 substitute_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 version_module (shared)
 vhost_alias_module (shared)
 dav_module (shared)
 dav_fs_module (shared)
 dav_lock_module (shared)
 lua_module (shared)
 mpm_prefork_module (shared)
 proxy_module (shared)
 lbmethod_bybusyness_module (shared)
 lbmethod_byrequests_module (shared)
 lbmethod_bytraffic_module (shared)
 lbmethod_heartbeat_module (shared)
 proxy_ajp_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_express_module (shared)
 proxy_fcgi_module (shared)
 proxy_fdpass_module (shared)
 proxy_ftp_module (shared)
 proxy_http_module (shared)
 proxy_scgi_module (shared)
 proxy_wstunnel_module (shared)
 systemd_module (shared)
 cgi_module (shared)
 passenger_module (shared)
 ruby_module (shared)
```

**Comment by mikeowens** [comment]
Ah. Well then it seems I need to find out where and why that is getting called when it is not being used. It may be that it's getting a turn in the request chain and is doing that init before it realizes its not being called. Therefore I need to move that some place after it knows for certain it's being called. I will try to figure that out today.

**Comment by calh** [comment]
Cool, thank you.  I'm also continuing to try and recreate this in a docker test case for you so that you can see it in action for yourself.

**Comment by mikeowens** [comment]
Ok try the latest. This should fix the problem.

**Comment by calh** [comment]
Works!  I pulled in your commit in my PR and retested.  The CGI vars are not populated and the Passenger/Sinatra app behaves normally.  Thank you!
